name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-mobile-tests:
   runs-on: macos-latest
   steps:
    - name: pull the project
      uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
          java-version: '15'
          distribution: 'temurin'
          cache: maven

    - name: Set up Appium
      run: |
         npm install -g appium@v2.0.0-rc.4
         appium driver install -uiautomator2-driver
         appium -v
#         appium &>/dev/null &

#    - name: Run appium android avd's
#      uses: reactivecircus/android-emulator-runner@v2
#      with:
#         api-level: 29
#         script: mvn clean test -DsuiteXmlFile=testng_mobile.xml -Pandroid


    - name: Build with Maven
      run: mvn clean test -DsuiteXmlFile=testng_mobile.xml -Pandroid
#
#    - name: Terminate Emulator
#      run: /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu kill
